### ISSUE TITLE
Not able to install on ubunto 18.4

### ISSUE THREAD

**Issue by djha983** [fujavica/Snort.NET#1]
Hi,

I am trying to install this on Ubuntu 18.04 and all goes smoothly however i am not able to run razor command and start webserver.

I followed the instruction in https://github.com/fujavica/Snort.NET/wiki/Install-instructions-for-Debian-%289.8%29 and stuck in step 4 of Snortnet Installation.When i run below command i get error.

./razor --urls=http://*:5000/
![image](https://user-images.githubusercontent.com/17782428/84754227-b656da80-afdd-11ea-91da-d844a92c5e7f.png)

please suggest how i can solve this issue.

**Comment by fujavica** [comment]
Hello, 

the "razor" executable should be located at **/linux-x64/razor** within the deployment package.

Please follow the updated instructions for Snortnet installation and the command should work.
